/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PreviewPlatformConversationState = "active" | "awaiting_response" | "errored";

export type PreviewPlatformEditBugStatus = "open" | "repairing" | "resolved";

export type PreviewPlatformEditMilestoneStatus = "blocked" | "committed" | "failed" | "pending" | "repair_pending" | "running";

export type PreviewPlatformEditTransactionStatus = "completed" | "completed_with_issues" | "failed" | "repair_pending" | "repairing" | "running";

export type PreviewPlatformJobStatus = "active" | "completed" | "failed" | "queued";

export type PreviewPlatformProjectStatus = "active" | "errored" | "processing" | "stopped";

export type PreviewPlatformRole = "assistant" | "system" | "tool" | "user";

export type PreviewPlatformTemplates = "react";

export type PreviewPlatformWorkflowJobStatus = "cancelled" | "completed" | "completed_with_issues" | "failed" | "pending" | "repair_pending" | "repairing" | "running" | "suspended";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PreviewPlatformAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface PreviewPlatformConversation {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  project_id: string;
  state: Generated<PreviewPlatformConversationState | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PreviewPlatformEditBug {
  affected_files: Generated<Json>;
  attempt_count: Generated<number>;
  bug_key: string;
  category: string;
  created_at: Generated<Timestamp>;
  diagnostic: string;
  id: Generated<string>;
  milestone_id: string | null;
  originating_run_id: string;
  repair_run_id: string | null;
  resolved_at: Timestamp | null;
  severity: string;
  status: Generated<PreviewPlatformEditBugStatus>;
  transaction_id: string;
  updated_at: Generated<Timestamp>;
  validator: string;
}

export interface PreviewPlatformEditMilestone {
  affected_files: Generated<Json>;
  commit_status: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  milestone_key: string;
  originating_run_id: string;
  sequence: number;
  status: Generated<PreviewPlatformEditMilestoneStatus>;
  transaction_id: string;
  updated_at: Generated<Timestamp>;
  validation_status: Generated<string>;
}

export interface PreviewPlatformEditTransaction {
  completed_at: Timestamp | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  manifest_path: string;
  originating_run_id: string;
  project_id: string;
  repair_attempt_count: Generated<number>;
  repair_budget: Generated<number>;
  staging_root: string;
  status: Generated<PreviewPlatformEditTransactionStatus>;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformJobs {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  error: string | null;
  id: string;
  retries: Generated<number | null>;
  state: Generated<PreviewPlatformJobStatus>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformMessage {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
  role: PreviewPlatformRole;
  sequence_number: Generated<Int8>;
  source_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformProject {
  active_port: number | null;
  container_name: string | null;
  created_at: Generated<Timestamp>;
  description: string;
  id: Generated<string>;
  name: string;
  preview_url: string | null;
  status: Generated<PreviewPlatformProjectStatus>;
  template: Generated<PreviewPlatformTemplates | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PreviewPlatformProjectBuild {
  artifact_url: string | null;
  completed_at: Timestamp | null;
  container_name: string | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  host_port: number;
  id: Generated<string>;
  image_name: string | null;
  job_id: string | null;
  logs: Json | null;
  project_id: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformProjectFile {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  path: string;
  project_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformProjectJobs {
  created_at: Generated<Timestamp>;
  error: string | null;
  id: string;
  project_id: string;
  retries: Generated<number | null>;
  state: Generated<PreviewPlatformJobStatus>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformSession {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface PreviewPlatformUser {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface PreviewPlatformVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface PreviewPlatformWorkflowRun {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  /**
   * Frontend approvalId for human-in-the-loop decisions
   */
  id: Generated<string>;
  project_id: string;
  /**
   * Mastra agent that owns the suspended approval run
   */
  resume_agent_id: string | null;
  /**
   * Suspended tool call identifier used to validate resumption
   */
  resume_tool_call_id: string | null;
  /**
   * Suspended tool name used for resumption diagnostics
   */
  resume_tool_name: string | null;
  run_id: string;
  status: Generated<PreviewPlatformWorkflowJobStatus | null>;
  /**
   * Mastra workflow snapshot captured when a workflow suspends
   */
  suspended_step: Json | null;
  updated_at: Generated<Timestamp>;
  workflow_id: string;
}

export interface DB {
  pgmigrations: Pgmigrations;
  "preview_platform.account": PreviewPlatformAccount;
  "preview_platform.conversation": PreviewPlatformConversation;
  "preview_platform.edit_bug": PreviewPlatformEditBug;
  "preview_platform.edit_milestone": PreviewPlatformEditMilestone;
  "preview_platform.edit_transaction": PreviewPlatformEditTransaction;
  "preview_platform.jobs": PreviewPlatformJobs;
  "preview_platform.message": PreviewPlatformMessage;
  "preview_platform.project": PreviewPlatformProject;
  "preview_platform.project_build": PreviewPlatformProjectBuild;
  "preview_platform.project_file": PreviewPlatformProjectFile;
  "preview_platform.project_jobs": PreviewPlatformProjectJobs;
  "preview_platform.session": PreviewPlatformSession;
  "preview_platform.user": PreviewPlatformUser;
  "preview_platform.verification": PreviewPlatformVerification;
  "preview_platform.workflow_run": PreviewPlatformWorkflowRun;
}
