/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type PreviewPlatformConversationState = "active" | "awaiting_response" | "errored";

export type PreviewPlatformJobStatus = "active" | "completed" | "failed" | "queued";

export type PreviewPlatformProjectStatus = "active" | "errored" | "processing" | "stopped";

export type PreviewPlatformRole = "assistant" | "system" | "tool" | "user";

export type PreviewPlatformTemplates = "react";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Pgmigrations {
  id: Generated<number>;
  name: string;
  run_on: Timestamp;
}

export interface PreviewPlatformAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface PreviewPlatformConversation {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  project_id: string;
  state: Generated<PreviewPlatformConversationState | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PreviewPlatformJobs {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  error: string | null;
  id: string;
  retries: Generated<number | null>;
  state: Generated<PreviewPlatformJobStatus>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformMessage {
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  message: string;
  role: PreviewPlatformRole;
  sequence_number: Generated<Int8>;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformProject {
  active_port: number | null;
  container_name: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  preview_url: string | null;
  status: Generated<PreviewPlatformProjectStatus>;
  template: Generated<PreviewPlatformTemplates | null>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PreviewPlatformProjectBuild {
  artifact_url: string | null;
  completed_at: Timestamp | null;
  container_name: string | null;
  created_at: Generated<Timestamp>;
  error: string | null;
  host_port: number;
  id: Generated<string>;
  image_name: string | null;
  job_id: string | null;
  logs: Json | null;
  project_id: string;
  started_at: Timestamp | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformProjectFile {
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  path: string;
  project_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformProjectJobs {
  created_at: Generated<Timestamp>;
  error: string | null;
  id: string;
  project_id: string;
  retries: Generated<number | null>;
  state: Generated<PreviewPlatformJobStatus>;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface PreviewPlatformSession {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface PreviewPlatformUser {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface PreviewPlatformVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  pgmigrations: Pgmigrations;
  "preview_platform.account": PreviewPlatformAccount;
  "preview_platform.conversation": PreviewPlatformConversation;
  "preview_platform.jobs": PreviewPlatformJobs;
  "preview_platform.message": PreviewPlatformMessage;
  "preview_platform.project": PreviewPlatformProject;
  "preview_platform.project_build": PreviewPlatformProjectBuild;
  "preview_platform.project_file": PreviewPlatformProjectFile;
  "preview_platform.project_jobs": PreviewPlatformProjectJobs;
  "preview_platform.session": PreviewPlatformSession;
  "preview_platform.user": PreviewPlatformUser;
  "preview_platform.verification": PreviewPlatformVerification;
}
